# Use uma imagem base do PHP
FROM php:8.2.12-apache

# Instala extensões que podem ser necessárias (caso precise de MySQL, por exemplo)
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Copia todos os arquivos para a pasta pública do Apache
COPY . /var/www/html/

# Exponha a porta 80 para o Apache
EXPOSE 80

# Inicie o Apache no container
CMD ["apache2-foreground"]
